services:
  - type: web
    name: unitree-server
    env: node
    rootDir: ./Unitree/server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    # Resource configuration
    plan: starter
    # Health check configuration
    healthCheckTimeout: 30
    healthCheckInterval: 30
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Will be set manually with Atlas connection string
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: UNIVERSITY_IP_PREFIX
        value: 10.22
      - key: UNIVERSITY_LAT
        value: 21.023883446210807
      - key: UNIVERSITY_LNG
        value: 105.79044010261333
      - key: UNIVERSITY_RADIUS
        value: 100
      - key: MIN_SESSION_DURATION
        value: 300
      - key: POINTS_PER_HOUR
        value: 60
      - key: TREE_COST
        value: 100
      - key: LOG_LEVEL
        value: info
      # Cloud Storage Configuration (Optional - set manually)
      - key: CLOUDINARY_CLOUD_NAME
        sync: de7fhgkqn
      - key: CLOUDINARY_API_KEY
        sync: 395491463937558
      - key: CLOUDINARY_API_SECRET
        sync: QPtKOVira1O1duGC9Ioc0mCw5dM
      # For mobile apps, use * or leave empty
      - key: CLIENT_URL
        value: "*"
      - key: CLIENT_DEV_URL
        value: "*"
      - key: CLIENT_URL_DEV
        value: "*"
      - key: CLIENT_URL_DEV_2
        value: "*" 