services:
  - type: web
    name: unitree-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Will be set manually with Atlas connection string
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: UNIVERSITY_IP_PREFIX
        value: 192.168
      - key: MIN_SESSION_DURATION
        value: 300
      - key: POINTS_PER_HOUR
        value: 60
      - key: TREE_COST
        value: 100
      - key: LOG_LEVEL
        value: info
      # These will be updated with actual deployed URLs
      - key: CLIENT_URL
        value: https://your-app-name.onrender.com
      - key: CLIENT_DEV_URL
        value: https://your-app-name.onrender.com
      - key: CLIENT_URL_DEV
        value: https://your-app-name.onrender.com
      - key: CLIENT_URL_DEV_2
        value: https://your-app-name.onrender.com 